### ISSUE TITLE
The given key 'assemblyPartLOTs' was not present in the dictionary.

### ISSUE THREAD

**Issue by FrostiDrinks** [yuwui/Uchu#16]
I just got a local server up and running, but when I try to load into the Avant Gardens I get thrown this error.

`[Error] System.Collections.Generic.KeyNotFoundException: The given key 'assemblyPartLOTs' was not present in the dictionary.
   at System.Collections.Generic.Dictionary``2.get_Item(TKey key)
   at InfectedRose.Lvl.LegoDataDictionary.get_Item(String key) in /mnt/d/vscode/Uchu/InfectedRose/InfectedRose.Lvl/LegoDataDictionary.cs:line 26
   at Uchu.World.Handlers.WorldInitializationHandler.<>c__DisplayClass9_0.<ItemContainerNode>b__1(InventoryItem i) in /mnt/d/vscode/Uchu/Uchu.World/Handlers/WorldInitializationHandler.cs:line 270
   at System.Linq.Enumerable.WhereSelectListIterator``2.ToArray()
   at Uchu.World.Handlers.WorldInitializationHandler.ItemContainerNode(Character character, InventoryType type) in /mnt/d/vscode/Uchu/Uchu.World/Handlers/WorldInitializationHandler.cs:line 267
   at Uchu.World.Handlers.WorldInitializationHandler.InventoryNode(Character character) in /mnt/d/vscode/Uchu/Uchu.World/Handlers/WorldInitializationHandler.cs:line 244
   at Uchu.World.Handlers.WorldInitializationHandler.GenerateCharacterXmlData(Character character) in /mnt/d/vscode/Uchu/Uchu.World/Handlers/WorldInitializationHandler.cs:line 223
   at Uchu.World.Handlers.WorldInitializationHandler.SendCharacterXmlDataToClient(Character character, IRakConnection connection, Session session) in /mnt/d/vscode/Uchu/Uchu.World/Handlers/WorldInitializationHandler.cs:line 189
   at Uchu.World.Handlers.WorldInitializationHandler.ClientLoadCompleteHandler(ClientLoadCompletePacket packet, IRakConnection connection) in /mnt/d/vscode/Uchu/Uchu.World/Handlers/WorldInitializationHandler.cs:line 122
   at Uchu.World.Handlers.WorldInitializationHandler.ClientLoadCompleteHandler(ClientLoadCompletePacket packet, IRakConnection connection) in /mnt/d/vscode/Uchu/Uchu.World/Handlers/WorldInitializationHandler.cs:line 139
   at Uchu.Core.Server.InvokeHandlerAsync(Handler handler, IRakConnection endPoint) in /mnt/d/vscode/Uchu/Uchu.Core/Server.cs:line 414
   at Uchu.Core.Server.HandlePacketAsync(IPEndPoint endPoint, Byte[] data, Reliability reliability) in /mnt/d/vscode/Uchu/Uchu.Core/Server.cs:line 340`

**Comment by Wincent01** [comment]
This has something to do with a built model you have. Can you provide any information about how you traveled to AG? Did you build a rocket and launch or did you use the /world command? If you built a rocket, did you notice anything weird about it?

Anyhow, I'll push a fix to this exception soon. Would need more information to know what caused it in the first place though.

**Comment by FrostiDrinks** [comment]
I built a rocket and launched from the far right launchpad in the tutorial area. I tried on a different character and went through the middle left launchpad and it loaded properly.

**Comment by FrostiDrinks** [comment]
I built a rocket and launched from the far right launchpad in the tutorial area. I tried on a different character and went through the middle left launchpad and it loaded properly.
