### ISSUE TITLE
Maelstrom Trench pirates don't smash well

### ISSUE THREAD

**Issue by MustacheMan2** [yuwui/Uchu#260]
When fighting Stromling Pirates in GF's Maelstrom Trench for the first play session, most will not drop loot and respawn, although they count towards achievements and missions (not every time).

**Comment by TheNexusAvenger** [comment]
Is this still a problem? The cache refactor may have resolved this, and it is fine from my local testing.

**Comment by RunningPlasmaDog** [comment]
I will go test. I noticed this the other day.

**Comment by RunningPlasmaDog** [comment]
I and TheNexusAvenger discovered this is still an issue.

**Comment by TheNexusAvenger** [comment]
I did re-test this not too long ago and did grab an exception when this happened. The messages are cut off due to how we log things, but enough information is there:
```
m.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)                                                                                                                  
[Error]         ---> System.NullReferenceException: Object reference not set to an instance of an object.
[Error]           at Uchu.World.MissionInventoryComponent.<>c__DisplayClass37_0.<<SmashAsync>b__0>d.MoveNext() in /Uchu.World/Objects/Components/Player/MissionInventoryComponent.cs:line 441
[Error]        --- End of stack trace from previous location ---
[Error]           at Uchu.World.MissionInventoryComponent.StartUnlockableAchievementsAsync[T](MissionTaskType type, Lot lot, Func`2 progress) in /Uchu.World/Objects/Components/Player/MissionInventoryComponent.cs:line 772
[Error]           at Uchu.World.MissionInventoryComponent.SmashAsync(Lot lot) in /Uchu.World/Objects/Components/Player/MissionInventoryComponent.cs:line 439
[Error]           at Uchu.World.DestructibleComponent.SmashAsync(GameObject smasher, Player owner, String animation) in /Uchu.World/Objects/Components/ReplicaComponents/DestructibleComponent.cs:line 156
[Error]           at Uchu.World.DestructibleComponent.<.ctor>b__20_2() in /Uchu.World/Objects/Components/ReplicaComponents/DestructibleComponent.cs:line 77
[Error]           --- End of inner exception stack trace ---
[Error]           at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellat
```

Haven't looked into why this happens, and won't for a little while. The code it points to suggests we store `null` mission task instances.
