### ISSUE TITLE
Character name Creation Crash

### ISSUE THREAD

**Issue by Dav-Sc** [yuwui/Uchu#344]
After creating a character and trying to set its name I get this error:
![image](https://user-images.githubusercontent.com/22717512/219829454-fe66331c-5e57-417b-8d0f-26d7c809364d.png)

[Error] [Char] Error when handling packet: System.IO.DirectoryNotFoundException: Could not find a part of the path
               'C:\Users\Dschi\DONOTDELETE\Documents\LegoUniverse\res\names\minifigname_first.txt'.
               at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess
               access, FileShare share, FileOptions options)
               at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access,
               FileShare share, FileOptions options, Int64 preallocationSize)
               at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access,
               FileShare share, FileOptions options, Int64 preallocationSize)
               at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess
               access, FileShare share, FileOptions options, Int64 preallocationSize)
               at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode
               mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64
               preallocationSize)
               at System.IO.File.ReadAllBytes(String path)
               at Uchu.Core.IO.LocalResources.GetStream(String path)
               at Uchu.Core.IO.LocalResources.ReadTextAsync(String path)
               at Uchu.Char.Handlers.CharacterHandler.CharacterCreate(CharacterCreateRequest packet, IRakConnection
               connection)
               at Uchu.Core.UchuServer.InvokeHandlerAsync(Handler handler, Object packet, IRakConnection endPoint)
               at Uchu.Core.UchuServer.HandlePacketAsync(IPEndPoint endPoint, Byte[] data, Reliability reliability)

I've been trying to debug it but I don't understand if its a client or server issue

**Comment by enteryournamehere** [comment]
Hi, this would be an issue with the client files you've set up Uchu to use. It is supposed to contain a file "minifigname_first.txt" inside the folder "names" inside the folder "res", but this seems to be missing for you. Ensure you acquired a complete client, the extraction process completed successfully, and you didn't accidentally move some files when you wanted to copy them.

**Comment by Dav-Sc** [comment]
This was entirely a user issue on my part. When I made the client folder I named is res bc I assumed it would be a resource for the server. And I pointed Uchu to the main client folder and not the true res sub folder

**Comment by enteryournamehere** [comment]
Ah right, easy mistake to make! Maybe we can add a check to Uchu to automatically accommodate for this.
