### ISSUE TITLE
Unhandled exception. Relation "Specifications" does not exist

### ISSUE THREAD

**Issue by Qiangong2** [yuwui/Uchu#5]
When I try to run Uchu.Master.dll, I get this error:

```
Unhandled exception. Npgsql.PostgresException (0x80004005): 42P01: relation "Specifications" does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Uchu.Master.MasterServer.Main(String[] args) in /home/kurt/Downloads/Uchu/Uchu.Master/MasterServer.cs:line 34
   at Uchu.Master.MasterServer.Main(String[] args) in /home/kurt/Downloads/Uchu/Uchu.Master/MasterServer.cs:line 45
   at Uchu.Master.MasterServer.<Main>(String[] args)
Aborted
```

Even when I comment out the offending lines, it does not work. Everything works up until now though

**Comment by Wincent01** [comment]
Commenting out offending lines is never the solution.

This issue is regarding a missing table in the database, something went wrong when building it with “dotnet ef database update -c UchuContext. Make sure all the tables are present in the database, and that your credentials are correct in the config file. Attempt to also drop the database and rebuild it.

I’d suggest looking into if you are perhaps using an outdated version of PostgreSQL, or the EntityFramework Command Line Interface, if the issue persists.
